var stories = [{"id":"dCwDN07Yu_6uP1MMpLfNnw9ymtbcM",
"label":"Texas coaching legend Darrell Royal dies",
"count":99},
{"id":"dyz3qwzZ2sgOlCMdLjLyi7Jlg0HNM",
"label":"Bears fans reportedly drank Nashville bars out of beer",
"count":91},
{"id":"dKVSoQifEzxlpSMN7ZRqoJLPPPYJM",
"label":"While you were sleeping: Euro trouble, US fiscal cliff",
"count":91},
{"id":"dBed-BHgcsE2zMMnC08pQUeBt6jyM",
"label":"Barcelona denied by Celtic wall",
"count":88},
{"id":"daPmYQL1jQB8NRM",
"label":"HTC and Verizon will unveil new device Nov. 13",
"count":88},
{"id":"dzaIilV9KoP4QAM5hSPllQlhNC59M",
"label":"Lions WR Calvin Johnson: Nerve injury has made it tough to grip ball",
"count":86},
{"id":"dftql6WfL4LRczMtmNJf_0uHmoc2M",
"label":"Chuck Sweeny: It's the ground game, stupid, for Obama's victory",
"count":81},
{"id":"dCpETFwm7VZFFLMLM26LceJvgXv7M",
"label":"Juan Martin del Potro v Janko Tipsarevic, ATP World Tour Finals: live",
"count":79},
{"id":"dH-u_FMOnMMFTGMUlqUcoIopbzhPM",
"label":"Bradley Wiggins, Tour de France champion, reportedly hit by car",
"count":78},
{"id":"dZkB9CcqbCznaaM3hRJQNKhQRIEZM",
"label":"Help spark Hurricane Sandy relief efforts",
"count":78},
{"id":"d7euRhQrRPYlLtM3Qac2awK79YCgM",
"label":"Angry Birds Star Wars Hits App Stores",
"count":78},
{"id":"dPD8lMVWZI35vaMntXOs5cEuEF_oM",
"label":"The 10 closest states in Election 2012",
"count":77},
{"id":"d35cRDJUiLbV2jMBTlerJ1vrz9pRM",
"label":"Microsoft Readying Office Edition For iOS, Android: Report",
"count":76},
{"id":"dw7Uoz_NXppC-PMBYINz9pbSL2aKM",
"label":"Adam Levine Excited by 'Baby-Making Music' on The Voice",
"count":73},
{"id":"dJM4VJvjLEcjYaMxU2F9lnZANgZOM",
"label":"How Gay Marriage Advocates Will Stop Worrying and Learn to Love the Ballot Box",
"count":72},
{"id":"dW8ca0PrRPYmGzMK8QVx2LTl_jLqM",
"label":"LA County Voters Asked to Weigh Condoms in Porn",
"count":71},
{"id":"dnoYBtYucjKeYiMkUMfyOfCYLEJeM",
"label":"OUR OPINION: Dangling over the fiscal cliff",
"count":71},
{"id":"dEG4C1HCPnuT8UMCpoj1dH4e1-DaM",
"label":"Move Over Obama, The Real Winner on Election Night",
"count":70},
{"id":"dVDFM8butL1eMuM8O_YpuKcEXXbIM",
"label":"Apple Loses FaceTime Patent Quibble",
"count":70},
{"id":"dTTxkOBkXg5uzCMkNBvnFtOZabBJM",
"label":"Celeb Romney Supporters Rant Online",
"count":69}];

var entities = [{"uri":"keyword:Regional",
"type":"enrycher:keyword",
"label":"Regional",
"count":62004},
{"uri":"keyword:North_America",
"type":"enrycher:keyword",
"label":"North_America",
"count":50590},
{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States",
"count":46894},
{"uri":"keyword:Society",
"type":"enrycher:keyword",
"label":"Society",
"count":39130},
{"uri":"keyword:Business",
"type":"enrycher:keyword",
"label":"Business",
"count":29342},
{"uri":"keyword:Society_and_Culture",
"type":"enrycher:keyword",
"label":"Society_and_Culture",
"count":19853},
{"uri":"http://en.wikipedia.org/wiki/United_States",
"type":"enrycher:location",
"label":"United States of America",
"count":17219},
{"uri":"keyword:Politics",
"type":"enrycher:keyword",
"label":"Politics",
"count":14904},
{"uri":"http://en.wikipedia.org/wiki/Barack_Obama",
"type":"enrycher:person",
"label":"President Barack Obama",
"count":14649},
{"uri":"dmoz:Regional/North_America/United_States/Government/Elections",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Government/Elections",
"count":13592},
{"uri":"http://en.wikipedia.org/wiki/Republican",
"type":"enrycher:organisation",
"label":"Republican",
"count":12904},
{"uri":"http://en.wikipedia.org/wiki/AP",
"type":"enrycher:organisation",
"label":"AP",
"count":12535},
{"uri":"http://en.wikipedia.org/wiki/Associated_Press",
"type":"enrycher:organisation",
"label":"Associated Press",
"count":11969},
{"uri":"dmoz:Society/Politics/Campaigns_and_Elections",
"type":"enrycher:category",
"label":"Society/Politics/Campaigns_and_Elections",
"count":11459},
{"uri":"dmoz:Regional/North_America/United_States/Government/Elections/President",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Government/Elections/President",
"count":11151},
{"uri":"dmoz:Regional/North_America/United_States/Society_and_Culture/Politics",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Society_and_Culture/Politics",
"count":11022},
{"uri":"keyword:Arts",
"type":"enrycher:keyword",
"label":"Arts",
"count":10945},
{"uri":"keyword:Sports",
"type":"enrycher:keyword",
"label":"Sports",
"count":10932},
{"uri":"keyword:United_Kingdom",
"type":"enrycher:keyword",
"label":"United_Kingdom",
"count":10334},
{"uri":"keyword:Shopping",
"type":"enrycher:keyword",
"label":"Shopping",
"count":10086}];

var search = {"articles":[{"id":150271,
"url":"http://www.poconorecord.com/apps/pbcs.dll/article?AID=/20121107/NEWS90/211070319/-1/rss29",
"title":"Obama's lease renewed despite tough economy",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"Pocono Record",
"country":"USA",
"city":"Stroudsburg",
"entities":[{"uri":"keyword:North_America",
"type":"enrycher:keyword",
"label":"North_America"},
{"uri":"dmoz:Society/History/By_Region/North_America/United_States/Presidents",
"type":"enrycher:category",
"label":"Society/History/By_Region/North_America/United_States/Presidents"},
{"uri":"http://en.wikipedia.org/wiki/Barack_Obama",
"type":"enrycher:person",
"label":"President Barack Obama"},
{"uri":"dmoz:Society/History/By_Region/North_America/United_States",
"type":"enrycher:category",
"label":"Society/History/By_Region/North_America/United_States"},
{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"}]},
{"id":150268,
"url":"http://www.wqow.com/story/20044461/eva-longoria-moved-to-tears-over-barack-obamas-re-election",
"title":"Eva Longoria \"moved to tears\" over Barack Obama's re-election",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"WQOW TV 18",
"country":"USA",
"city":"Eau Claire",
"entities":[{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"dmoz:Regional/North_America/United_States/Government/Elections",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Government/Elections"},
{"uri":"http://en.wikipedia.org/wiki/Eva_Longoria_Parker",
"type":"enrycher:person",
"label":"Eva Longoria"},
{"uri":"keyword:North_America",
"type":"enrycher:keyword",
"label":"North_America"},
{"uri":"dmoz:Regional/North_America/United_States/Government/Elections/President",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Government/Elections/President"}]},
{"id":150256,
"url":"http://www.poconorecord.com/apps/pbcs.dll/article?AID=/20121107/NEWS/121109835/-1/rss29",
"title":"Obama, Romney split Monroe and Pike counties",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"Pocono Record",
"country":"USA",
"city":"Stroudsburg",
"entities":[{"uri":"dmoz:Shopping/Home_and_Garden/Flags_and_Banners",
"type":"enrycher:category",
"label":"Shopping/Home_and_Garden/Flags_and_Banners"},
{"uri":"keyword:Reference",
"type":"enrycher:keyword",
"label":"Reference"},
{"uri":"keyword:Flags",
"type":"enrycher:keyword",
"label":"Flags"},
{"uri":"dmoz:Reference/Flags",
"type":"enrycher:category",
"label":"Reference/Flags"},
{"uri":"dmoz:Reference/Flags/Regional",
"type":"enrycher:category",
"label":"Reference/Flags/Regional"}]},
{"id":150255,
"url":"http://www.poconorecord.com/apps/pbcs.dll/article?AID=/20121107/NEWS90/121109832/-1/rss29",
"title":"Democrats, Latinos flexed muscle for Obama in Pa.",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"Pocono Record",
"country":"USA",
"city":"Stroudsburg",
"entities":[{"uri":"dmoz:Regional/North_America/United_States/Society_and_Culture/Politics/Parties",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Society_and_Culture/Politics/Parties"},
{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"http://en.wikipedia.org/wiki/Pennsylvania",
"type":"enrycher:location",
"label":"Pennsylvania"},
{"uri":"http://en.wikipedia.org/wiki/Barack_Obama",
"type":"enrycher:person",
"label":"President Barack Obama"},
{"uri":"dmoz:Regional/North_America/United_States/Pennsylvania/Society_and_Culture",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Pennsylvania/Society_and_Culture"}]},
{"id":150252,
"url":"http://www.poconorecord.com/apps/pbcs.dll/article?AID=/20121108/NEWS90/211080315/-1/rss29",
"title":"Obama has a cliff to avoid, Cabinet to pick",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"Pocono Record",
"country":"USA",
"city":"Stroudsburg",
"entities":[{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"dmoz:Regional/North_America/United_States/Arizona/Society_and_Culture/Politics",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Arizona/Society_and_Culture/Politics"},
{"uri":"enrycherann:speaker_john_boehner",
"type":"enrycher:person",
"label":"Speaker John Boehner"},
{"uri":"http://en.wikipedia.org/wiki/Republican",
"type":"enrycher:organisation",
"label":"Republican"},
{"uri":"dmoz:Regional/North_America/United_States/Society_and_Culture/Politics/Parties",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Society_and_Culture/Politics/Parties"}]},
{"id":150241,
"url":"http://www.poconorecord.com/apps/pbcs.dll/article?AID=/20121108/NEWS/211080325/-1/rss29",
"title":"Election a bad dream for Pocono Republicans",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"Pocono Record",
"country":"USA",
"city":"Stroudsburg",
"entities":[{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"dmoz:Society/Politics/Campaigns_and_Elections",
"type":"enrycher:category",
"label":"Society/Politics/Campaigns_and_Elections"},
{"uri":"http://en.wikipedia.org/wiki/Republican",
"type":"enrycher:organisation",
"label":"Republican"},
{"uri":"keyword:Regional",
"type":"enrycher:keyword",
"label":"Regional"},
{"uri":"dmoz:Regional/North_America/United_States/Government/Elections",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Government/Elections"}]},
{"id":150239,
"url":"http://www.poconorecord.com/apps/pbcs.dll/article?AID=/20121108/NEWS/211080326/-1/rss29",
"title":"Obama repeats in Monroe County",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"Pocono Record",
"country":"USA",
"city":"Stroudsburg",
"entities":[{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"dmoz:Society/Politics/Campaigns_and_Elections",
"type":"enrycher:category",
"label":"Society/Politics/Campaigns_and_Elections"},
{"uri":"http://en.wikipedia.org/wiki/Elizabeth_Monroe",
"type":"enrycher:location",
"label":"Monroe County"},
{"uri":"http://en.wikipedia.org/wiki/Republican",
"type":"enrycher:organisation",
"label":"Republican"},
{"uri":"keyword:North_America",
"type":"enrycher:keyword",
"label":"North_America"}]},
{"id":150235,
"url":"http://www.poconorecord.com/apps/pbcs.dll/article?AID=/20121108/NEWS/211080327/-1/rss29",
"title":"Election notebook: Students get real-life experience as eligible voters",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"Pocono Record",
"country":"USA",
"city":"Stroudsburg",
"entities":[{"uri":"dmoz:Society/Politics/Campaigns_and_Elections",
"type":"enrycher:category",
"label":"Society/Politics/Campaigns_and_Elections"},
{"uri":"keyword:Politics",
"type":"enrycher:keyword",
"label":"Politics"},
{"uri":"dmoz:Business/Transportation_and_Logistics/Traffic_Control",
"type":"enrycher:category",
"label":"Business/Transportation_and_Logistics/Traffic_Control"},
{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"http://en.wikipedia.org/wiki/Chris",
"type":"enrycher:person",
"label":"Chris"}]},
{"id":150228,
"url":"http://www.poconorecord.com/apps/pbcs.dll/article?AID=/20121107/NEWS90/211070320/-1/rss29",
"title":"Casey defeats deep-pocketed tea party backer",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"Pocono Record",
"country":"USA",
"city":"Stroudsburg",
"entities":[{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"dmoz:Regional/North_America/United_States/Society_and_Culture/Politics/Parties",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Society_and_Culture/Politics/Parties"},
{"uri":"http://en.wikipedia.org/wiki/Bob_Casey_%28baseball_announcer%29",
"type":"enrycher:person",
"label":"Bob Casey"},
{"uri":"enrycherann:u.s._senate",
"type":"enrycher:person",
"label":"U.S. Senate"},
{"uri":"http://en.wikipedia.org/wiki/Pennsylvania",
"type":"enrycher:location",
"label":"Pennsylvania"}]},
{"id":150198,
"url":"http://www.kansascity.com/2012/11/08/3906654/stocks-turn-lower-on-wall-street.html#storylink=rss",
"title":"Stocks slide on Wall Street, extending sell-off",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"Kansas City Star",
"country":"USA",
"city":"Kansas City",
"entities":[{"uri":"dmoz:Business/Investing/Stocks_and_Bonds",
"type":"enrycher:category",
"label":"Business/Investing/Stocks_and_Bonds"},
{"uri":"keyword:Investing",
"type":"enrycher:keyword",
"label":"Investing"},
{"uri":"http://en.wikipedia.org/wiki/United_States",
"type":"enrycher:location",
"label":"United States of America"},
{"uri":"keyword:Business",
"type":"enrycher:keyword",
"label":"Business"},
{"uri":"dmoz:Business/Investing/Stocks_and_Bonds/Equities",
"type":"enrycher:category",
"label":"Business/Investing/Stocks_and_Bonds/Equities"}]},
{"id":150149,
"url":"http://www.wqow.com/story/20029781/election-over-us-stocks-dip-on-challenges-to-come",
"title":"Election over, US stocks dip on challenges to come",
"language":"eng",
"date":"2012-11-08T21:55:00",
"source":"WQOW TV 18",
"country":"USA",
"city":"Eau Claire",
"entities":[{"uri":"dmoz:Business/Investing/Stocks_and_Bonds",
"type":"enrycher:category",
"label":"Business/Investing/Stocks_and_Bonds"},
{"uri":"keyword:Investing",
"type":"enrycher:keyword",
"label":"Investing"},
{"uri":"http://en.wikipedia.org/wiki/Lenore_Romney",
"type":"enrycher:person",
"label":"Romney"},
{"uri":"keyword:Business",
"type":"enrycher:keyword",
"label":"Business"},
{"uri":"dmoz:Science/Technology/Energy",
"type":"enrycher:category",
"label":"Science/Technology/Energy"}]},
null,
{"id":150133,
"url":"http://www.idahostatesman.com/2012/11/06/2336976/boise-library-offered-a-place.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+IdahostatesmancomLocalNews+%28IdahoStatesman.com+Local+News%29",
"title":"Boise library offered a place for public to plug into election",
"language":"eng",
"date":"2012-11-08T21:55:00",
"source":"Idaho Statesman",
"country":"USA",
"city":"Boise",
"entities":[{"uri":"dmoz:Society/Politics/Campaigns_and_Elections",
"type":"enrycher:category",
"label":"Society/Politics/Campaigns_and_Elections"},
{"uri":"keyword:Reference",
"type":"enrycher:keyword",
"label":"Reference"},
{"uri":"http://en.wikipedia.org/wiki/Casey_McGehee",
"type":"enrycher:person",
"label":"Casey McGee"},
{"uri":"http://en.wikipedia.org/wiki/Boise,_Idaho",
"type":"enrycher:organisation",
"label":"Boise Public"},
{"uri":"dmoz:Reference/Libraries",
"type":"enrycher:category",
"label":"Reference/Libraries"}]},
{"id":150104,
"url":"http://www.thecorryjournal.com/articles/2012/11/08/news/doc5092a3ec14973230508435.txt",
"title":"A look ahead to the 2013 election",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"Corry Journal",
"country":"USA",
"city":"Corry",
"entities":[{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"dmoz:Regional/North_America/United_States/Society_and_Culture/Politics/Candidates_and_Campaigns",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Society_and_Culture/Politics/Candidates_and_Campaigns"},
{"uri":"http://en.wikipedia.org/wiki/Corry",
"type":"enrycher:location",
"label":"Corry"},
{"uri":"http://en.wikipedia.org/wiki/Massachusetts",
"type":"enrycher:location",
"label":"Massachusetts"},
{"uri":"http://en.wikipedia.org/wiki/Romney",
"type":"enrycher:person",
"label":"Romney"}]},
{"id":150086,
"url":"http://www.thecorryjournal.com/articles/2012/11/08/news/doc509406827d552348848148.txt",
"title":"Voters in Warren, Crawford counties will focus on race for U.S. president",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"Corry Journal",
"country":"USA",
"city":"Corry",
"entities":[{"uri":"dmoz:Regional/North_America/United_States/Government/Elections",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Government/Elections"},
{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"http://en.wikipedia.org/wiki/Romney",
"type":"enrycher:person",
"label":"Romney"},
{"uri":"http://en.wikipedia.org/wiki/United_States",
"type":"enrycher:location",
"label":"United States of America"},
{"uri":"http://en.wikipedia.org/wiki/Warren_County",
"type":"enrycher:location",
"label":"Warren County"}]},
{"id":150079,
"url":"http://www.idahostatesman.com/2012/11/07/2337069/in-idaho-presidential-result-means.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+IdahostatesmancomLocalNews+%28IdahoStatesman.com+Local+News%29",
"title":"In Idaho, presidential result means more Obamacare, likely less federal spending",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"Idaho Statesman",
"country":"USA",
"city":"Boise",
"entities":[{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"dmoz:Regional/North_America/United_States/Idaho",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Idaho"},
{"uri":"http://en.wikipedia.org/wiki/Idaho",
"type":"enrycher:organisation",
"label":"Idaho Education Association"},
{"uri":"http://en.wikipedia.org/wiki/Beth",
"type":"enrycher:person",
"label":"Beth"},
{"uri":"keyword:North_America",
"type":"enrycher:keyword",
"label":"North_America"}]},
null,
null,
null,
null],
"entities":[{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"keyword:North_America",
"type":"enrycher:keyword",
"label":"North_America"},
{"uri":"keyword:Regional",
"type":"enrycher:keyword",
"label":"Regional"},
{"uri":"http://en.wikipedia.org/wiki/Barack_Obama",
"type":"enrycher:person",
"label":"President Barack Obama"},
{"uri":"dmoz:Regional/North_America/United_States/Government/Elections",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Government/Elections"},
{"uri":"dmoz:Society/History/By_Region/North_America/United_States/Presidents",
"type":"enrycher:category",
"label":"Society/History/By_Region/North_America/United_States/Presidents"},
{"uri":"http://en.wikipedia.org/wiki/Republican",
"type":"enrycher:organisation",
"label":"Republican"},
{"uri":"keyword:Society",
"type":"enrycher:keyword",
"label":"Society"},
{"uri":"http://en.wikipedia.org/wiki/United_States",
"type":"enrycher:location",
"label":"United States of America"},
{"uri":"dmoz:Society/Politics/Campaigns_and_Elections",
"type":"enrycher:category",
"label":"Society/Politics/Campaigns_and_Elections"},
{"uri":"keyword:Politics",
"type":"enrycher:keyword",
"label":"Politics"},
{"uri":"keyword:Society_and_Culture",
"type":"enrycher:keyword",
"label":"Society_and_Culture"},
{"uri":"dmoz:Regional/North_America/United_States/Government/Elections/President",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Government/Elections/President"},
{"uri":"http://en.wikipedia.org/wiki/Romney",
"type":"enrycher:person",
"label":"Romney"},
{"uri":"dmoz:Regional/North_America/United_States/Society_and_Culture/Politics",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Society_and_Culture/Politics"},
{"uri":"dmoz:Regional/North_America/United_States/Society_and_Culture/Politics/Candidates_and_Campaigns",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Society_and_Culture/Politics/Candidates_and_Campaigns"},
{"uri":"dmoz:Regional/North_America/United_States/Society_and_Culture/Politics/Parties",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Society_and_Culture/Politics/Parties"},
{"uri":"http://en.wikipedia.org/wiki/Associated_Press",
"type":"enrycher:organisation",
"label":"Associated Press"},
{"uri":"dmoz:Regional/North_America/United_States/Government/Elections/President/2008",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Government/Elections/President/2008"},
{"uri":"http://en.wikipedia.org/wiki/Congress",
"type":"enrycher:organisation",
"label":"Congress"}],
"stories":[{"id":"dKVSoQifEzxlpSMN7ZRqoJLPPPYJM",
"label":"While you were sleeping: Euro trouble, US fiscal cliff"},
{"id":"dX9koyKXh5E02PMi05adysp4qgYOM",
"label":"Four more years for battle-hardened Obama"},
{"id":"dl2BSdx5ZLsT1CMFkhNfdUMdhn4oM",
"label":"Romney's Pennsylvania chase: State's Republicans trying hard to believe"},
{"id":"dPD8lMVWZI35vaMntXOs5cEuEF_oM",
"label":"The 10 closest states in Election 2012"},
{"id":"dl2BSdx5ZLsT1CMUObll0T0PmnPbM",
"label":"Obama projected as winner in Wisconsin, Pennsylvania"},
{"id":"dm3m2fb6swRtSMMpieRB2keRuwYUM",
"label":"Media Circus: Fox Struggles With Obama's Win"},
{"id":"dsSSP3gc68EfJBMQAqDVfXaPvsI_M",
"label":"Nation awaits result from pivotal swing state Ohio"},
{"id":"dziYYZI50d-ovXMFGRqOa0r9Rsm7M",
"label":"THE SCENE IN HOBOKEN"},
{"id":"dnoYBtYucjKeYiMkUMfyOfCYLEJeM",
"label":"OUR OPINION: Dangling over the fiscal cliff"},
{"id":"dEG4C1HCPnuT8UMCpoj1dH4e1-DaM",
"label":"Move Over Obama, The Real Winner on Election Night"},
{"id":"dTTxkOBkXg5uzCMkNBvnFtOZabBJM",
"label":"Celeb Romney Supporters Rant Online"},
{"id":"dDGuSA-IXGWBlnMnxkVW5zpcbxnlM",
"label":"Election Results from A to Z"},
{"id":"dr_Rd8bWYC49MkMcwC37cpHpU6rZM",
"label":"The 2012 Election Gender Gap - Why Obama Won, Why Romney Lost"},
{"id":"ddQbgLwiAkJgNsM8o-I3vbrQf_NxM",
"label":"Analysts View: Markets react to the election"},
{"id":"dftql6WfL4LRczMtmNJf_0uHmoc2M",
"label":"Chuck Sweeny: It's the ground game, stupid, for Obama's victory"},
{"id":"dGd_iHkRpyER3bMTanRFvUXxaisgM",
"label":"Euro Pressured by Greeks Decision - DailyForex.com"},
{"id":"d4YGJlO0aSnLP_M81AOOnT8vvo37M",
"label":"Obama Wins 2nd Term, Xi Jinping to Lead China"},
{"id":"dEFZ4ypeXbHaT_MqwIshnpNuhpHUM",
"label":"Obama, Congress Begin Budget Negotiations"},
{"id":"dRIU5wSCCfYAgxM89UhA6dwT4A6pM",
"label":"On the day after, Republicans ask what went wrong"},
{"id":"dRIU5wSCCfYAgxMC9UxfIEGSD3zEM",
"label":"The Republican civil war"}]};

var entityQuery = {"uri":"keyword:Sports",
"type":"enrycher:keyword",
"label":"Sports",
"articles":[{"id":150231,
"url":"http://espn.go.com/blog/bigten/post/_/id/64558/live-chat-gameday-thursday-10",
"title":"Live chat: GameDay Thursday",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"ESPN",
"country":"USA",
"city":"Dallas/Fort Worth"},
null,
{"id":150196,
"url":"http://www.carlukegazette.co.uk/sport/local-sport/four-titles-for-callum-1-2618493",
"title":"Four titles for Callum",
"language":"eng",
"date":"2012-11-08T21:56:00",
"source":"Carluke Gazette",
"country":"United Kingdom",
"city":"Carluke"},
null,
{"id":150171,
"url":"http://www.kansascity.com/2012/11/07/3906030/gms-discuss-more-replay-september.html#storylink=rss",
"title":"GMs discuss more replay, September roster changes",
"language":"eng",
"date":"2012-11-08T21:55:00",
"source":"Kansas City Star",
"country":"USA",
"city":"Kansas City"},
{"id":150128,
"url":"http://www.cbs3springfield.com/story/20041876/usc-manager-fired-for-deflating-balls-in-loss",
"title":"USC manager fired for deflating balls in loss",
"language":"eng",
"date":"2012-11-08T21:55:00",
"source":"WSHM TV 3",
"country":"USA",
"city":"Springfield"},
{"id":150111,
"url":"http://www.cbs3springfield.com/story/20043367/henry-suspended-for-substance-abuse-violation",
"title":"Henry suspended for substance abuse violation",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"WSHM TV 3",
"country":"USA",
"city":"Springfield"},
{"id":150103,
"url":"http://www.cbs3springfield.com/story/20037495/gms-discuss-more-replay-september-roster-changes",
"title":"GMs discuss more replay, September roster changes",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"WSHM TV 3",
"country":"USA",
"city":"Springfield"},
null,
{"id":150080,
"url":"http://www.cbs3springfield.com/story/20043506/nhl-union-hold-labor-talks-a-3rd-straight-day",
"title":"NHL, union hold labor talks a 3rd straight day",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"WSHM TV 3",
"country":"USA",
"city":"Springfield"},
{"id":150075,
"url":"http://www.myfoxal.com/story/20045879/priceline-to-acquire-kayak-in-18-billion-deal",
"title":"Priceline to acquire Kayak in $1.8 billion deal",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"WBRC TV 6",
"country":"USA",
"city":"Birmingham"},
{"id":150072,
"url":"http://www.cbs3springfield.com/story/20045182/brown-tries-to-become-nhras-1st-black-champion",
"title":"Brown tries to become NHRA's 1st black champion",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"WSHM TV 3",
"country":"USA",
"city":"Springfield"},
{"id":150062,
"url":"http://www.cbs3springfield.com/story/20045618/canada-1-2-at-skeleton-world-cup-after-2-runs",
"title":"Canada 1-2 at skeleton World Cup after 2 runs",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"WSHM TV 3",
"country":"USA",
"city":"Springfield"},
{"id":150054,
"url":"http://www.cbs3springfield.com/story/20045880/this-seasons-nfl-rookies-as-good-as-any-group",
"title":"This season's NFL rookies 'as good as any group'",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"WSHM TV 3",
"country":"USA",
"city":"Springfield"},
{"id":150045,
"url":"http://www.cbs3springfield.com/story/20045249/camilo-villegas-shares-early-lead-at-disney",
"title":"Villegas, Gainey share early lead at Disney",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"WSHM TV 3",
"country":"USA",
"city":"Springfield"},
{"id":150043,
"url":"http://www.cbs3springfield.com/story/20037600/walt-weiss-hired-as-colorado-rockies-manager",
"title":"Walt Weiss hired as Colorado Rockies manager",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"WSHM TV 3",
"country":"USA",
"city":"Springfield"},
{"id":150041,
"url":"http://www.sportrider.com/features/146_1212_rider_preventative_maintenance/",
"title":"Rider's Preventative Maintenance",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"Sport Rider magazine",
"country":"USA",
"city":""},
null,
{"id":150017,
"url":"http://www.sportrider.com/industry_news/146_1211_roadrace_factory_school_coming_to_sonoma_ca/",
"title":"RoadRace Factory School Coming to Sonoma, CA",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"Sport Rider magazine",
"country":"USA",
"city":""},
{"id":150002,
"url":"http://www.walesonline.co.uk/news/welsh-politics/welsh-politics-news/2012/11/07/committee-unconvinced-welsh-govt-can-afford-its-own-spending-plans-91466-32185911/",
"title":"Committee \"unconvinced\" Welsh Govt can afford its own spending plans",
"language":"eng",
"date":"2012-11-08T21:54:00",
"source":"Wales on Sunday",
"country":"United Kingdom",
"city":"Cardiff"}],
"stories":[{"id":"dH-u_FMOnMMFTGMUlqUcoIopbzhPM",
"label":"Bradley Wiggins, Tour de France champion, reportedly hit by car"},
{"id":"ddh9c7nKa6AKw6MdZKZFjUV7bw0rM",
"label":"Patience key at demanding Singapore Open"},
{"id":"dBed-BHgcsE2zMMnC08pQUeBt6jyM",
"label":"Barcelona denied by Celtic wall"},
{"id":"d5HL0CDPrQqBhsMIzdw5B9S-Mu0yM",
"label":"Raptors vs. Thunder final score: Oklahoma City bounces back with 108-88 victory"},
{"id":"dJIGkbyvRVZD-LMVmp9Vags6thpSM",
"label":"Garrigus looks good for Disney"},
{"id":"dQnKUykDzVOTCLM",
"label":"South African champ tests positive for banned drug"},
{"id":"dZR9y-Csg9HvIPMXtVgAtUOdzGcaM",
"label":"Danny Granger Out For 3 Months"},
{"id":"dCwDN07Yu_6uP1MMpLfNnw9ymtbcM",
"label":"Texas coaching legend Darrell Royal dies"},
{"id":"d5nlPmfa4ktfNDMD2EtESURnROa8M",
"label":"Hostility Lingers Over Handling of Marathon"},
{"id":"dlKG5ZiqW4UzmnMgxge9CPMG4ClIM",
"label":"NHL and Union to Meet Again on Wednesday"},
{"id":"dzaIilV9KoP4QAM5hSPllQlhNC59M",
"label":"Lions WR Calvin Johnson: Nerve injury has made it tough to grip ball"},
{"id":"dt-nAXEWh0x_hiMYTJUPkgTGChltM",
"label":"Week 10 in Fantasy Football: Colts vs. Jaguars"},
{"id":"dyz3qwzZ2sgOlCMdLjLyi7Jlg0HNM",
"label":"Bears fans reportedly drank Nashville bars out of beer"},
{"id":"dw7Uoz_NXppC-PMBYINz9pbSL2aKM",
"label":"Adam Levine Excited by 'Baby-Making Music' on The Voice"},
{"id":"dF2z1FDniP9jkwM6Iqxx9In97l8UM",
"label":"Sugar Bowl in New Orleans to Host Big 12-SEC Game"},
{"id":"dumsSxrjpuW6pqMeyakdMDWx3vYfM",
"label":"Jason Bay And The Mets Are, Mercifully, Getting A Divorce"},
{"id":"d0w4tKsYXYUBZ8M77ZOdiuG4tZoEM",
"label":"Weiss slight favorite to manage Rockies"},
{"id":"d2NVhTzplm0IYPM0MZempNnEisPkM",
"label":"Colts Shave Heads to Support Coach Pagano"},
{"id":"dVY8AaeCq6zpe9MqFwcsEyLXPWkEM",
"label":"Video: AccuScore report for Pats-Bills"},
{"id":"dCpETFwm7VZFFLMLM26LceJvgXv7M",
"label":"Juan Martin del Potro v Janko Tipsarevic, ATP World Tour Finals: live"}],
"entities":[{"uri":"keyword:Sports",
"type":"enrycher:keyword",
"label":"Sports"},
{"uri":"keyword:Regional",
"type":"enrycher:keyword",
"label":"Regional"},
{"uri":"keyword:Games",
"type":"enrycher:keyword",
"label":"Games"},
{"uri":"keyword:North_America",
"type":"enrycher:keyword",
"label":"North_America"},
{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"keyword:Society",
"type":"enrycher:keyword",
"label":"Society"},
{"uri":"keyword:Business",
"type":"enrycher:keyword",
"label":"Business"},
{"uri":"dmoz:Sports/Football/American/NFL",
"type":"enrycher:category",
"label":"Sports/Football/American/NFL"},
{"uri":"keyword:Video_Games",
"type":"enrycher:keyword",
"label":"Video_Games"},
{"uri":"dmoz:Games/Video_Games/Recreation/Browser_Based",
"type":"enrycher:category",
"label":"Games/Video_Games/Recreation/Browser_Based"},
{"uri":"keyword:Motorsports",
"type":"enrycher:keyword",
"label":"Motorsports"},
{"uri":"keyword:Football",
"type":"enrycher:keyword",
"label":"Football"},
{"uri":"keyword:Recreation",
"type":"enrycher:keyword",
"label":"Recreation"},
{"uri":"keyword:Baseball",
"type":"enrycher:keyword",
"label":"Baseball"},
{"uri":"dmoz:Sports/Paintball/Teams",
"type":"enrycher:category",
"label":"Sports/Paintball/Teams"},
{"uri":"dmoz:Sports/Equestrian/Racing",
"type":"enrycher:category",
"label":"Sports/Equestrian/Racing"},
{"uri":"dmoz:Sports/Baseball/Youth/Leagues/Little_League",
"type":"enrycher:category",
"label":"Sports/Baseball/Youth/Leagues/Little_League"},
{"uri":"keyword:College_and_University",
"type":"enrycher:keyword",
"label":"College_and_University"},
{"uri":"keyword:Shopping",
"type":"enrycher:keyword",
"label":"Shopping"},
{"uri":"dmoz:Sports/Fantasy",
"type":"enrycher:category",
"label":"Sports/Fantasy"}]};

var storyQuery = {"id":"dCwDN07Yu_6uP1MMpLfNnw9ymtbcM",
"label":"Texas coaching legend Darrell Royal dies",
"articles":[null,
{"id":142200,
"url":"http://www.nytimes.com/2012/11/08/sports/ncaafootball/darrell-royal-texas-coach-who-pioneered-wishbone-offense-dies-at-88.html?pagewanted=all&_r=1&",
"title":"Darrell Royal, Texas Coach Who Pioneered Wishbone Offense, Dies at 88",
"language":"eng",
"date":"2012-11-08T20:26:00",
"source":"New York Times",
"country":"USA",
"city":""},
{"id":141848,
"url":"http://www.sfgate.com/news/texas/article/A-sampling-of-colorful-Darrell-Royal-quotes-4018555.php",
"title":"A sampling of colorful Darrell Royal quotes",
"language":"eng",
"date":"2012-11-08T20:24:00",
"source":"San Francisco Chronicle",
"country":"USA",
"city":"San Francisco"},
{"id":141824,
"url":"http://www.sfgate.com/sports/article/Ex-Texas-coach-Royal-dies-at-age-88-4018744.php",
"title":"Ex-Texas coach Royal dies at age 88",
"language":"eng",
"date":"2012-11-08T20:24:00",
"source":"San Francisco Chronicle",
"country":"USA",
"city":"San Francisco"},
{"id":139893,
"url":"http://www.newson6.com/story/20031518/former-texas-coach-and-sooner-all-american-darrell-royal-dies",
"title":"Former Texas Coach And Sooner All-American Darrell Royal Dies",
"language":"eng",
"date":"2012-11-08T20:12:00",
"source":"KOTV TV 6",
"country":"USA",
"city":"Tulsa"},
{"id":138449,
"url":"http://www.stltoday.com/sports/other/sports-digest-former-texas-football-coach-darrell-royal-dies/article_68f7032d-acb7-54b7-ad14-97d916977053.html",
"title":"Sports digest: Former Texas football coach Darrell Royal dies",
"language":"eng",
"date":"2012-11-08T20:05:00",
"source":"South County Journal",
"country":"USA",
"city":"Warrenton"},
{"id":137398,
"url":"http://bleacherreport.com/articles/1399678-darrell-royal-remembering-former-texas-coach-and-wishbone-innovator",
"title":"Darrell Royal: Remembering Former Texas Coach and Wishbone Innovator",
"language":"eng",
"date":"2012-11-08T19:59:00",
"source":"Bleacher Report",
"country":"USA",
"city":""},
{"id":137155,
"url":"http://www.bizjournals.com/sanantonio/blog/2012/11/texas-football-legend-darrell-royal.html",
"title":"Texas football legend Darrell Royal dead at 88",
"language":"eng",
"date":"2012-11-08T19:57:00",
"source":"Boston Business Journal",
"country":"USA",
"city":"Albany"},
{"id":136390,
"url":"http://www.washingtonpost.com/blogs/early-lead/wp/2012/11/07/darrell-royal-legendary-texas-coach-dies-at-88/",
"title":"Darrell K. Royal (shown in a 2007 photo) has died. (Harry Cabluck / AP)",
"language":"eng",
"date":"2012-11-08T19:52:00",
"source":"Washington Post",
"country":"USA",
"city":""},
{"id":131578,
"url":"http://www.latimes.com/sports/sportsnow/la-sp-sn-darrell-royal-texas-20121107,0,4677344.story?track=rss",
"title":"Former football coach Darrell Royal was royalty in Texas",
"language":"eng",
"date":"2012-11-08T19:24:00",
"source":"Los Angeles Times",
"country":"USA",
"city":""},
{"id":124211,
"url":"http://www.bizjournals.com/houston/news/2012/11/07/winningest-coach-in-ut-football.html",
"title":"Darrell Royal, 'winningest' coach in UT football history, dies at 88",
"language":"eng",
"date":"2012-11-08T18:37:00",
"source":"Boston Business Journal",
"country":"USA",
"city":"Albany"},
{"id":116344,
"url":"http://www.chicagotribune.com/sns-rt-usa-sportstexas-update-1l1e8m7jg0-20121107,0,4880658.story",
"title":"UPDATE 1-University of Texas football coaching legend Darrell Royal dies",
"language":"eng",
"date":"2012-11-08T17:51:00",
"source":"Chicago Tribune",
"country":"USA",
"city":""},
{"id":114007,
"url":"http://www.mercurynews.com/other-sports/ci_21953186/sports-digest-ex-texas-football-coach-darrell-royal",
"title":"Sports digest: Ex-Texas football coach Darrell Royal dies at 88",
"language":"eng",
"date":"2012-11-08T17:36:00",
"source":"Sunnyvale Sun",
"country":"USA",
"city":"Pacifica"},
{"id":113284,
"url":"http://espn.go.com/blog/dallas/colleges/post/_/id/4680575/derrick-dockery-remembers-darrell-royal",
"title":"Derrick Dockery remembers Darrell Royal",
"language":"eng",
"date":"2012-11-08T17:32:00",
"source":"ESPN",
"country":"USA",
"city":"Dallas/Fort Worth"},
{"id":109087,
"url":"http://www2.tbo.com/sports/sports/2012/nov/08/spsporto3-texas-icon-royal-dead-at-88-ar-558540/",
"title":"Texas icon Royal dead at 88",
"language":"eng",
"date":"2012-11-08T17:05:00",
"source":"Sun City Sun",
"country":"USA",
"city":"Sun City"},
{"id":106558,
"url":"http://www.chicagotribune.com/sports/sns-tsn-afn-royal-texas-p1-20121107,0,1325713.story",
"title":"Former Texas coach Darrell Royal dies",
"language":"eng",
"date":"2012-11-08T16:50:00",
"source":"Chicago Tribune",
"country":"USA",
"city":""},
null,
null,
{"id":104868,
"url":"http://www.mysanantonio.com/news/local_news/article/Coach-s-influence-resonates-with-Coker-Franchione-4018306.php",
"title":"Coach's influence resonates with Coker, Franchione",
"language":"eng",
"date":"2012-11-08T16:40:00",
"source":"San Antonio Northwest Weekly",
"country":"USA",
"city":"San Antonio"},
{"id":103068,
"url":"http://www.mysanantonio.com/news/local_news/article/UT-s-Royal-dies-at-88-4018367.php",
"title":"UT's Royal dies at 88",
"language":"eng",
"date":"2012-11-08T16:30:00",
"source":"San Antonio Northwest Weekly",
"country":"USA",
"city":"San Antonio"}],
"relatedArticles":[],
"entities":[{"uri":"http://en.wikipedia.org/wiki/Darrell_Royal",
"type":"enrycher:person",
"label":"Darrell Royal"},
{"uri":"keyword:North_America",
"type":"enrycher:keyword",
"label":"North_America"},
{"uri":"http://en.wikipedia.org/wiki/Alexis_Texas",
"type":"enrycher:organisation",
"label":"Texas Workforce Commission"},
{"uri":"dmoz:Regional/North_America/United_States/Texas/Recreation_and_Sports",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Texas/Recreation_and_Sports"},
{"uri":"keyword:Regional",
"type":"enrycher:keyword",
"label":"Regional"},
{"uri":"dmoz:Regional/Europe/United_Kingdom/Society_and_Culture/Military",
"type":"enrycher:category",
"label":"Regional/Europe/United_Kingdom/Society_and_Culture/Military"},
{"uri":"keyword:United_States",
"type":"enrycher:keyword",
"label":"United_States"},
{"uri":"dmoz:Health/Alternative/Coaching",
"type":"enrycher:category",
"label":"Health/Alternative/Coaching"},
{"uri":"keyword:Sports",
"type":"enrycher:keyword",
"label":"Sports"},
{"uri":"dmoz:Regional/Europe/United_Kingdom/Society_and_Culture/Military/Veterans",
"type":"enrycher:category",
"label":"Regional/Europe/United_Kingdom/Society_and_Culture/Military/Veterans"},
{"uri":"http://en.wikipedia.org/wiki/Austin,_Texas",
"type":"enrycher:location",
"label":"Austin"},
{"uri":"dmoz:Regional/North_America/United_States/Texas/Society_and_Culture",
"type":"enrycher:category",
"label":"Regional/North_America/United_States/Texas/Society_and_Culture"},
{"uri":"keyword:Health",
"type":"enrycher:keyword",
"label":"Health"},
{"uri":"dmoz:Health/Alternative/Coaching/North_America",
"type":"enrycher:category",
"label":"Health/Alternative/Coaching/North_America"},
{"uri":"http://en.wikipedia.org/wiki/Southwest_Conference",
"type":"enrycher:location",
"label":"Southwest Conference"},
{"uri":"http://en.wikipedia.org/wiki/Oklahoma",
"type":"enrycher:location",
"label":"Oklahoma"},
{"uri":"keyword:United_Kingdom",
"type":"enrycher:keyword",
"label":"United_Kingdom"},
{"uri":"keyword:Texas",
"type":"enrycher:keyword",
"label":"Texas"},
{"uri":"dmoz:Sports/Football/American/College_and_University",
"type":"enrycher:category",
"label":"Sports/Football/American/College_and_University"},
{"uri":"dmoz:Sports/Football/American",
"type":"enrycher:category",
"label":"Sports/Football/American"}]};